name: Release new version

on:
  workflow_dispatch:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc

      - name: Install & Build
        run: |
          npm ci
          npm run package

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: vscode-chronoly-extension
          path: "./chronoly-${{ github.event.inputs.version }}.vsix"

      - name: Create release
        id: create-release
        run: |
          # Define variables for paths and names
          VSIX_PATH="./chronoly-${{ github.event.inputs.version }}.vsix"
          VSIX_NAME="chronoly-${{ github.event.inputs.version }}.vsix"

          # Create the release
          gh release create "${{ github.ref_name }}" --draft --title "Release ${{ github.ref_name }}" \
            "$VSIX_PATH#$VSIX_NAME"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  vscode-publish:
    name: Publish to VS Code Marketplace
    needs: build
    environment: publish-vscode-marketplace
    runs-on: ubuntu-latest
    env:
      VS_MARKETPLACE_PAT: ${{ secrets.VS_MARKETPLACE_PAT }}
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: vscode-chronoly-extension

      - name: Publish to Registry
        run: |
          npx @vscode/vsce publish -p $VS_MARKETPLACE_PAT --packagePath *.vsix